# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DocAgentAi < Formula
  desc "Multi-platform documentation workflow agent installer"
  homepage "https://github.com/zeshone/doc-agent-ai"
  version "3.3.0-rc2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zeshone/doc-agent-ai/releases/download/v3.3.0-rc2/doc-agent-ai_3.3.0-rc2_darwin_amd64.tar.gz"
      sha256 "6857ecb90dc9940d9bdc0ea499252c458788a90a5f29cfba9ac2a922e0cfe9cb"

      define_method(:install) do
        bin.install "doc-agent-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zeshone/doc-agent-ai/releases/download/v3.3.0-rc2/doc-agent-ai_3.3.0-rc2_darwin_arm64.tar.gz"
      sha256 "30e5b34aeee3791ad63c28bd8433114d196de729d7179aa4a0b01265f470966e"

      define_method(:install) do
        bin.install "doc-agent-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zeshone/doc-agent-ai/releases/download/v3.3.0-rc2/doc-agent-ai_3.3.0-rc2_linux_amd64.tar.gz"
      sha256 "5be551982f6dcc8c1ecec75fe6bb1fcebd8f08aef324a2f343eac49150c0698f"
      define_method(:install) do
        bin.install "doc-agent-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zeshone/doc-agent-ai/releases/download/v3.3.0-rc2/doc-agent-ai_3.3.0-rc2_linux_arm64.tar.gz"
      sha256 "e611489df8b15bb0d7312345f0e49ef7ec7de9fdd0f412f41ae8e703ad9750e1"
      define_method(:install) do
        bin.install "doc-agent-ai"
      end
    end
  end

  test do
    system "#{bin}/doc-agent-ai --version"
  end
end
