# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DocAgentAi < Formula
  desc "Multi-platform documentation workflow agent installer"
  homepage "https://github.com/zeshone/doc-agent-ai"
  version "3.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zeshone/doc-agent-ai/releases/download/v3.3.0/doc-agent-ai_3.3.0_darwin_amd64.tar.gz"
      sha256 "b5b71a1639acd953f02a875a37b9692dbf05d08126bedb8b1563c4fefc0f1b35"

      define_method(:install) do
        bin.install "doc-agent-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zeshone/doc-agent-ai/releases/download/v3.3.0/doc-agent-ai_3.3.0_darwin_arm64.tar.gz"
      sha256 "0d81a7b0dad95486ef57937a91cfd78b4bca4a31f30fd9a4df1b2e20522e4913"

      define_method(:install) do
        bin.install "doc-agent-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zeshone/doc-agent-ai/releases/download/v3.3.0/doc-agent-ai_3.3.0_linux_amd64.tar.gz"
      sha256 "b1aac5c1abee43a56d2cbf322e8ff92152801bcc1739eac95e051dc6ed59cc33"
      define_method(:install) do
        bin.install "doc-agent-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zeshone/doc-agent-ai/releases/download/v3.3.0/doc-agent-ai_3.3.0_linux_arm64.tar.gz"
      sha256 "8fbc9c1c163df86b754491949faa255c8e459343d3a17e42424af88405d45888"
      define_method(:install) do
        bin.install "doc-agent-ai"
      end
    end
  end

  test do
    system "#{bin}/doc-agent-ai --version"
  end
end
