# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DocAgentAi < Formula
  desc "Multi-platform documentation workflow agent installer"
  homepage "https://github.com/zeshone/doc-agent-ai"
  version "3.3.0-rc3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zeshone/doc-agent-ai/releases/download/v3.3.0-rc3/doc-agent-ai_3.3.0-rc3_darwin_amd64.tar.gz"
      sha256 "fb16680ebc0924ceab799a36a81884a8b177666bb381b9c2959eb3b1d162cc9f"

      define_method(:install) do
        bin.install "doc-agent-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zeshone/doc-agent-ai/releases/download/v3.3.0-rc3/doc-agent-ai_3.3.0-rc3_darwin_arm64.tar.gz"
      sha256 "93e8feeab32a48a77a3aaef169c9c5e8bff2b0cde71e9e9634c11ea4860f2d63"

      define_method(:install) do
        bin.install "doc-agent-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zeshone/doc-agent-ai/releases/download/v3.3.0-rc3/doc-agent-ai_3.3.0-rc3_linux_amd64.tar.gz"
      sha256 "f3b0aceb4686aac32714c05de101c6d3e565b3d257aef39131a21ab486838d2b"
      define_method(:install) do
        bin.install "doc-agent-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zeshone/doc-agent-ai/releases/download/v3.3.0-rc3/doc-agent-ai_3.3.0-rc3_linux_arm64.tar.gz"
      sha256 "62a6741f2dcabefac76ec8d5e7c7f5e7e7b7772f6c01a8d1bba59e4300e9dcc6"
      define_method(:install) do
        bin.install "doc-agent-ai"
      end
    end
  end

  test do
    system "#{bin}/doc-agent-ai --version"
  end
end
